//
//  Product.swift
//  H&I Personalized Medicine
//
//  Created by Marcus Grant on 10/21/22.
//

import Foundation

struct Product: Identifiable {
    var id = UUID()
    var name: String
    var image: String
    var author: String
    var price: Int
    var details: String
    var ingredients: String
    var suggestedUse: String
}

var productList = [Product(name: "B CompleteX", image: "BCompleteX", author: "By: HummingbirdX", price: 45, details: "-Supports Carbohydrate Metabolism \n-Supports Healthy Nervous System/Adrenal/Immune Function \n-Supports Cardiovascular Health \n-Supports Healthy Mental Function and Mood", ingredients: "Amount Per Serving % Daily Value: \n-Thiamin (as thiamine HCl) 20 mg 1667% \n-Riboflavin (as riboflavin 5’-phosphate sodium) 20 mg 1538%  \n-Niacin (130 mg as niacinamide and 10 mg as niacin) 140 mg 875%  \n-Vitamin B6 (as pyridoxal-5’-phosphate) 20 mg 1176%  \n-Folate (as Quatrefolic® (6S)-5-methyltetrahydrofolic acid, glucosamine salt) 400 mcg DFE 100%", suggestedUse: "Take one capsule once or twice daily, or as directed by your healthcare practitioner."),
                   Product(name: "MagMaxX", image: "MagMaxX", author: "By: HummingbirdX", price: 32, details: "-Supports Cardiovascular Health \n-Supports Healthy Muscle Function/Healthy Nerve Conduction. \n-Supports Bone Health. \n-Supports Energy Production. \n-May Support Healthy Glucose Metabolism.", ingredients: "Serving Size: 2 Capsules. \n-Servings Per Container: 60. \n-Magnesium (as Albion® di-magnesium malate and TRAACS® magnesium lysinate glycinate chelate) 250 mg 60%. \n-Malic Acid (as Albion® di-magnesium malate) 828 mg.", suggestedUse: "Take one to two capsules twice daily at or between meals, or as directed by your healthcare professional."),
                   Product(name: "OmegaCOQ10", image: "OmegaCOQ10 MaxX", author: "By: HummingbirdX", price: 73, details: "-Supports Health/Function of the Cardiovascular System. \n-Helps Maintain Natural Plasma/Tissue CoQ10 Levels. \n-Monoglyceride Fish Oil for a 3x Greater Absorption of EPA and DHA.", ingredients: "-MaxSimil® Fish Oil Concentrate 250 mg. \n-Total Omega-3 Fatty Acids 174 mg. \n-EPA (eicosapentaenoic acid) 115 mg. \n-DHA (docosahexaenoic acid) 50 mg. \n-Kaneka Q10® Coenzyme Q10 (as ubiquinone) 50 mg.", suggestedUse: "Take one softgel twice per day, or as directed by your healthcare professional."),
                   Product(name: "ALA BerberineX", image: "ALA BerberineX", author: "By: HummingbirdX", price: 62, details: "-Supports Glucose Metabolism and Insulin Sensitivity. \n-Supports Healthy Blood Lipid Metabolism. \n-Assists the Body in Maintaining Normal Levels of HbA1c. \n-Positively Influences Adipocyte Differentiation and PPAR Expression. \n-Associated waith Adipogenesis. \n-Provides Antioxidant Support.", ingredients: "-Biotin 450 mcg 1,500%. \n-Alpha-Lipoic Acid 600 mg.", suggestedUse: "Take two capsules twice daily, or as directed by your healthcare practitioner."),
                   Product(name: "Mag CitrateX", image: "Mag CitrateX", author: "By: HummingbirdX", price: 28, details: "-Supports Carbohydrate Metabolism \n-Supports the Numerous Metabolic Activities of Magnesium in the Body \n-Facilitates Bowel Movement \n-Helps Prevent Calcium Crystallization in the Kidneys", ingredients: "-Magnesium (as magnesium citrate) 100 mg 24.", suggestedUse: "Take one capsule daily, or as directed by your healthcare practitioner."),
                   Product(name: "DigestiveX", image: "DigestiveX", author: "By: HummingbirdX", price: 26, details: "-Supports Healthy Digestion of Macronutrients and Enhances Nutrient Absorption. \n-Supports Breakdown of Polysaccharides in Beans and Cruciferous Vegetables. \n-Helps Support Pancreatic and Brush Border Enzyme Function. \n-Supports Breakdown of Lactose.", ingredients: "-Amount Per Serving % Daily Value. \n-Protease (pH 3.0-9.0) 120,000 HUT. \n-Papain (from papaya) 50,000 TU. \n-Bromelain (from pineapple) 120 GDU. Amylase 4,000 SKB. \n-Amyloglucosidase (glucoamylase) 30 AG.", suggestedUse: "Take one to two capsules daily, or use as directed by your healthcare practitioner. If necessary, capsules may be opened and contents sprinkled over food."),
                   Product(name: "FiberAbsorbX", image: "FiberAbsorbX", author: "By: HummingbirdX", price: 45, details: "-Supports Satiety. \n-Supports Weight Control. \n-Supports Glucose Metabolism. \n-Supports Cholesterol Metabolism. \n-Supports Healthy Bowel Movements. \n-Serves as a Prebiotic for Intestinal Bacteria.", ingredients: "-Dietary Fiber (from propolmannan) (Amorphophallus konjac) (tuber) 3 g 11%.", suggestedUse: "Take three to six capsules once per day, or take three capsules 30 to 60 minutes before each of your two biggest meals, or use as directed by your healthcare professional."),
                   Product(name: "Betaine HCl with Pepsin", image: "Betaine HCl with Pepsin 120 capsules", author: "Designs for Health", price: 32, details: "This product is ideal for those who are looking to support their stomach’s digestive function. Taking one capsule before a meal aids digestion‚ especially the digestion of protein-containing foods‚ and helps with the assimilation of nutrients.", ingredients: "-Betaine Hydrochloride (HCL) 750mg. \n-Pepsin 1:10‚000 50mg.", suggestedUse: "As a dietary supplement‚ take one capsule per day before a meal‚ or as directed by your healthcare practitioner."),
                   Product(name: "HTP Synergy vegetarian capsules", image: "5 HTP Synergy Vegetarian Capsules", author: "By: Designs for Health", price: 34, details: "-The feel good hormone. \n-Serotonin precursor. \n-Well absorbed.", ingredients: "-Vitamin B-6 (As Pyridoxal-5-Phosphate). \n-5-HTP (5-Hydroxytryptophan).", suggestedUse: "As a dietary supplement‚ take one capsule per day‚ or as directed by your healthcare practitioner."),
                   Product(name: "Acetyl L Carnitins vegetarian capsules", image: "Acetyl L Carnitine 90 vegetarian capsule", author: "By: Designs for Health", price: 43, details: "-Natural component of our brain's chemistry \n-Support energy production. \n-Crosses the blood-brain barrier.", ingredients: "-Acetyl L-Carnitine.", suggestedUse: "As a dietary supplement, take one capsule per day, or as directed by your healthcare practitioner."),
                   Product(name: "Adrenal Complex 240 capsules", image: "Adrenal Complex 240 capsules", author: "By: Designs for Health", price: 80, details: "Adrenal Complex is a glandular-based product designed to support overall adrenal function. It is fortified with N-acetyl tyrosine, vitamin C and a comprehensive spectrum of B vitamins. Adrenal Complex is ideal for those under chronic stress due to its ability to balance cortisol and replenish catecholamines (dopamine, norepinephrine, and epinephrine).", ingredients: "-Vitamin C (As Ascorbic Acid) 100mg / 170%. \n-Thiamin (Vitamin B-1) (As Thaimin HCI) 2mg / 130%. \n-Riboflavin (Vitamin B-2) (As Riboflavin-5-Phosphate) 5mg / 290%. \n-Vitamin B-6 (As Pyridoxal-5-Phosphate) 5mg / 250%. \n-Pantothenic Acid (As D-Calcium Pantothenate) 250mg / 2500%. \n-Whole Adrenal Glandular 200mg. \n-PABA (Para-Aminobenzoic Acid) 100mg. \n-N-Acetyl-L-Tyrosine 50mg. \n-Adrenal Cortex Glandular 50mg.", suggestedUse: "As a dietary supplement‚ take two capsules per day with meals‚ or as directed by your healthcare practitioner."),
                   Product(name: "Adrenal Complex™ 120 capsules", image: "Adrenal Complex™ 120 capsules", author: "By: Designs for Health", price: 45, details: "-Support Your Adrenals. \n-Energy-Promoting Nutrients. \n-ADAPTOGENIC Herbs.", ingredients: "-Vitamin C (As Ascorbic Acid). \n-Thiamin (Vitamin B-1) (As Thiamine HCI). \n-Riboflavin (Vitamin B-2) (As Riboflavin-5-Phosphate). \n-Vitamin B-6 (As Pyridoxal-5-Phosphate). \n-Pantothenic Acid (As D-Calcium Pantothenate). \n-Whole Adrenal Glandular. \n-PABA (Para-Aminobenzoic Acid). \n-N-Acetyl-L-Tyrosine. \n-Adrenal Cortex Glandular.", suggestedUse: "As a dietary supplement‚ take two capsules per day with meals‚ or as directed by your healthcare practitioner."),
                   Product(name: "AllerGzyme vegetarian capsules", image: "AllerGzyme 60 vegetarian capsules", author: "By: Designs for Health", price: 42, details: "-Support For The Modern Diet. \n-Assists With The Digeestion of Protein. \n-Powerful Key Ingredients.", ingredients: "-Glutalytic® 350mg. \n-Endo-Peptidase Complex 75‚000 HUT/500 SAPU. \n-Exo-Peptidase Complex 125 DPPIV. \n-Protease (Bacillus subtilis) 30‚000 PC. \n-Bromelain (Ananas Comosus) (Stem) 500‚000 PU.", suggestedUse: "As a dietary supplement‚ take one capsule with each protein-containing meal per day‚ or as directed by your healthcare practitioner."),
                   Product(name: "Amino Acid Supreme", image: "Amino Acid Supreme", author: "By: Designs for Health", price: 70, details: "Amino Acid Supreme™ is a high potency, balanced, free-form amino acid formula in a great-tasting orange flavored powder. It provides amino acids which are considered to be “essential,” meaning they cannot be made in the body and, thus, must be obtained through diet or supplementation.", ingredients: "-Vitamin B-6 (As Pyridoxal-5-Phosphate) 20mg / 1176%. \n-L-Leucine 715mg/. \n-L-Phenylalanine 715mg. \n-L-Phenylalanine 715mg. \n-L-Valine 615mg. \n-L-Histidine 590mg. \n-L-Lysine 525mg. \n-L-Arginine 525mg. \n-L-Isoleucine 525mg. \n-Alpha-Ketoglutarate 470mg. \n-L-Methionine 435mg. L-Threonine 385mg.", suggestedUse: "As a dietary supplement‚ mix 7 grams (approx. two teaspoons) in 8-10 ounces of water per day‚ or as directed by your healthcare practitioner."),
                   Product(name: "B-Supreme 120 capsules", image: "B-Supreme 120 capsules", author: "By: Designs for Health", price: 48, details: "-Synergistic Formula. \n-Naturally Occuring Folates. \n-Synergistic Formula.", ingredients: "-Vitamin B1. \n-Vitamin B2. \n-Vitamin B3. \n-Vitamin B6. \n-Folates. \n-Vitamin B5. \n-Biotin. \n-Choline. \n-Trimethylglycine.", suggestedUse: "As a dietary supplement, take one capsule per day with a meal, or as directed by your healthcare practitioner."),
                   Product(name: "Berberine Synergy 60 vegetarian capsules", image: "Berberine Synergy 60 vegetarian capsules", author: "By: Designs for Health", price: 48, details: "-Optimal Glucose Levels. \n-Strong Berberine And ALA Combination. \n-Supportive Antioxidant.", ingredients: "-Berberine (As Berberine HCI) (Berberis Aristata) (Root) 400mg. \n-Alpha Lipoic Acid 100mg.", suggestedUse: "As a dietary supplement‚ take one capsule per day with a meal‚ or as directed by your health care practitioner."),
                   Product(name: "Betaine HCl with Pepsin 120 capsules", image: "Betaine HCl with Pepsin 120 capsules", author: "By: Designs for Health", price: 32, details: "-Required For The Proper Absorbtion Of Nutrients. \n-Support Digestive Function. \n-Well absorbed.", ingredients: "-Vitamin B-6 (As Pyridoxal-5-Phosphate). \n-5-HTP (5-Hydroxytryptophan).", suggestedUse: "As a dietary supplement‚ take one capsule per day‚ or as directed by your healthcare practitioner."),
                   Product(name: "Betaine HCl with Pepsin 120 capsules", image: "5 HTP Synergy Vegetarian Capsules", author: "By: Designs for Health", price: 34, details: "-Required For The Proper Absorbtion Of Nutrients. \n-Support Digestive Function.", ingredients: "-Betaine Hydrochloride (HCL) 750mg. \n-Pepsin 1:10‚000 50mg.", suggestedUse: "As a dietary supplement‚ take one capsule per day before a meal‚ or as directed by your healthcare practitioner."),
                   Product(name: "C3 Curcumin Complex 60 vegetarian capsules.", image: "C3 Curcumin Complex 60 vegetarian capsules.", author: "By: Designs for Health", price: 50, details: "-Strongest, Most Protective. \n-Concentrated Curcumin. \n-Enhanced Absorption.", ingredients: "-Curcumin C3 Complex® (Curcuma Longa) (Rhizomes) 400mg.", suggestedUse: "As a dietary supplement‚ take one capsule per day‚ or as directed by your healthcare practitioner."),
                   Product(name: "Carnitine Synergy 120 capsules", image: "Carnitine Synergy 120 capsules", author: "By: Designs for Health", price: 34, details: "-Increase fat burning capabilities. \n-Lowers cholesterol levels and triglycerides. \n-Promotes heart health. \n-Promotes healthy liver function. \n-Enhance mental focus and memory. \n-Increase in energy levels. \n-Reduce food cravings. \n-Enhances long and short term memory. \n-Support in weight loss. \n-Help to combat chronic fatigue.", ingredients: "-L-Carnitine (from L-Carnitine Tartrate) 400mg. \n-Acetyl-L-Carnitine 100mg. \n-Daily Value not established.", suggestedUse: "As a dietary supplement, take one to four capsules daily before meals or as directed by your health care practitioner."),
                   Product(name: "5 HTP Synergy 90 vegetarian capsules", image: "5 HTP Synergy Vegetarian Capsules", author: "By: Designs for Health", price: 34, details: "-The feel good hormone. \n-Serotonin precursor. \n-Well absorbed.", ingredients: "-Vitamin B-6 (As Pyridoxal-5-Phosphate). \n-5-HTP (5-Hydroxytryptophan).", suggestedUse: "As a dietary supplement‚ take one capsule per day‚ or as directed by your healthcare practitioner."),
]
